include:
    -   template: Jobs/Secret-Detection.gitlab-ci.yml

stages:
    - test
    - announce

.test_job: &test_job
    stage: test
    script:
        - phing test
    cache:
        paths:
            - vendor/
    services:
        - name: memcached:1-alpine
          alias: memcached
        - name: redis:7-alpine
          alias: redis
    variables:
        MEMCACHED_HOST: memcached
        REDIS_HOST: redis

test:php8.3:
    <<: *test_job
    image: nexendrie/php:8.3

test:php8.4:
    <<: *test_job
    image: nexendrie/php:8.4

test:reports:
    extends:
        - .test_job
    image: nexendrie/php:8.4
    variables:
        REPORTS: 1
    coverage: '/(\d+\%) covered/'
    artifacts:
        paths:
            - coverage.xml
            - junit.xml
            - phpstan.json
        reports:
            coverage_report:
                coverage_format: cobertura
                path: coverage.xml
            junit: junit.xml
            codequality: phpstan.json

announce:gitlab:
    stage: announce
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    rules:
        - if: $CI_COMMIT_TAG
    script:
        - echo "Creating GitLab release"
    release:
        tag_name: $CI_COMMIT_TAG
        name: "Version $CI_COMMIT_TAG"
        description: "./RELEASE_NOTES"
